module.exports = {
  dimensions: false,
  memo: true,
  ref: true,
  svgo: true,
  svgoConfig: {
    // with the changes from @svgr/cli 5.5.0 we had to use the syntax
    // below to remove XMLNS attributes https://github.com/gregberge/svgr/issues/475
    plugins: [
      {
        removeAttrs: {
          attrs: [
            "path:fill",
            "path:class",
            "path:stroke",
            "clipPath:id",
            "g:clip-path",
          ],
        },
        removeXMLNS: true,
      },
    ],
    cleanupAttrs: true,
    inlineStyles: false,
    removeDoctype: true,
    removeXMLProcInst: true,
    removeComments: true,
    removeMetadata: true,
    removeTitle: true,
    removeDesc: true,
    removeUselessDefs: true,
    removeEditorsNSData: true,
    removeEmptyAttrs: true,
    removeHiddenElems: true,
    removeEmptyText: true,
    removeEmptyContainers: true,
    removeViewBox: false,
    cleanupEnableBackground: true,
    minifyStyles: true,
    convertStyleToAttrs: true,
    convertColors: true,
    convertPathData: true,
    convertTransform: true,
    removeUnknownsAndDefaults: true,
    removeNonInheritableGroupAttrs: true,
    removeUselessStrokeAndFill: true,
    removeUnusedNS: true,
    prefixIds: true,
    cleanupIDs: true,
    cleanupNumericValues: true,
    cleanupListOfValues: true,
    moveElemsAttrsToGroup: true,
    moveGroupAttrsToElems: true,
    collapseGroups: true,
    removeRasterImages: true,
    mergePaths: true,
    convertShapeToPath: true,
    convertEllipseToCircle: true,
    sortAttrs: true,
    sortDefsChildren: true,
    removeDimensions: true,
    removeAttrs: true,
    removeAttributesBySelector: true,
    removeElementsByAttr: true,
    addClassesToSVGElement: true,
    addAttributesToSVGElement: true,
    removeOffCanvasPaths: true,
    removeStyleElement: true,
    removeScriptElement: true,
    reusePaths: true,
  },
  svgProps: {
    fill: "currentColor",
    "aria-hidden": true,
  },
}
